version: '3'
services:

  keycloak_db_sso:
    image: postgres:11.2-alpine
    environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}
    networks:
      service_sso_net:
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - keycloak_sso_vol:/var/lib/postgresql/data

  keycloak:
    image: 'quay.io/keycloak/keycloak:${KC_VERSION}'
    hostname: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db_sso:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_HOSTNAME_STRICT: 'false'
      KC_HOSTNAME_STRICT_HTTPS: 'false'
      # DB_SCHEMA: public
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    command: start-dev
    networks:
      service_sso_net:
    ports:
      - "${KEYCLOAK_PORT}:8080"
    depends_on: 
      - keycloak_db_sso
  
  # for PHP example uncomment this service if using PHP
  service_app:
    build:
      context: ./service/php
      dockerfile: Dockerfile
    restart: always
    networks:
      service_sso_net:
    env_file: 
      - .env
    ports: 
      - ${SERVICE_PORT}:80
    volumes: 
      - ./service/php:/var/www/html/

networks:
  service_sso_net:

volumes: 
  keycloak_sso_vol:
